apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-agendamento-app
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://rds-fiap-hackathon-2.cktpwpbhuxkf.us-east-1.rds.amazonaws.com:3306/agendamentodb
  SPRING_JPA_SHOW: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  AWS_SQS_URI: https://sqs.us-east-1.amazonaws.com/354919765289/agendamento-consulta.fifo
  AWS_SQS_NAME: agendamento-consulta.fifo
  URI_API_AGENDA: http://svc-agenda-app/agenda-app